#!/bin/bash

# Grateful for the answers on http://stackoverflow.com/questions/34447348
shopt -s nullglob

JSON_COLLECT() {
	jq ".end.sum_$1.bits_per_second / 8" < "$j"
}

DIVIDEND() {
	for line in $(echo "$1")
		do
			# "awk '{ print sprintf("%.0f", $1); }'" rounds down the values to remove decimals to be able to sum
			echo "$line" | awk '{ print sprintf("%.0f", $1); }'
		# "awk '{sum+=$0} END{print sum}'" sums the output values
		done | awk '{sum+=$0} END{print sum}'
}

DIVISOR() {
	echo "$1" | wc -w
}

QUOTIENT() {
	echo $(( $@ ))
}

## Working out the average
#hsent=$(cat *.json | jq '.end.sum_sent.bits_per_second / 8') #JSON_COLLECT function instead of this

# SENT



echo \$data \<\<EOD
for j in *.json
do
	dt=$(basename "$j" .json)
	if jq -e '.error' < $j
	then
		echo $(readlink $j) has an error, skipping >&2
		cat $j >&2
		continue
	fi

	DIVISOR=$(ls -hal | wc -l | tr -d '[:space:]')

	SENT_HOURLY=$(JSON_COLLECT sent)
	SENT_DIVIDEND=$(DIVIDEND "$SENT_HOURLY")
	#SENT_DIVISOR=$(DIVISOR "$SENT_HOURLY")
	#SENT_QUOTIENT=$(QUOTIENT "$SENT_DIVIDEND / $SENT_DIVISOR")
	SENT_QUOTIENT=$(QUOTIENT "$SENT_DIVIDEND / $DIVISOR")

	RECEIVED_HOURLY=$(JSON_COLLECT received)
	RECEIVED_DIVIDEND=$(DIVIDEND "$RECEIVED_HOURLY")
	#RECEIVED_DIVISOR=$(DIVISOR "$RECEIVED_HOURLY")
	#RECEIVED_QUOTIENT=$(QUOTIENT "$RECEIVED_DIVIDEND / $RECEIVED_DIVISOR")
	RECEIVED_QUOTIENT=$(QUOTIENT "$RECEIVED_DIVIDEND / $DIVISOR")

	echo "$dt" "$SENT_QUOTIENT" "$RECEIVED_QUOTIENT"
done
echo EOD

cat << END
set term svg size 1920,945 fname "Helvetica Neue"
set title "Generated by https://github.com/CalebSargeant/iperf3chart, forked from https://github.com/kaihendry/iperf3chart"
set style data histogram
set style histogram cluster gap 1
set style fill solid border -1
set boxwidth 0.9
set xtic rotate by -90 scale 0 font ",8"
set key top left

# Convert bytes to megabytes
set format y '%.0s %cB'

plot \$data using 2:xticlabels(strftime("%Y-%m-%d",column(1))) t 'up', '' u 3 t 'down'
END
